# List all books (GET)
GET http://localhost/v3/books
Content-Type: application/json

###

# Search books (GET)
GET http://localhost/v3/books/search?title=Test&author=AuthorName&publisher=PublisherName
Content-Type: application/json

###

# Show a specific book (GET)
GET http://localhost/v3/books/1
Content-Type: application/json

###

# Rent a book (POST)
POST http://localhost/v3/books/1/rent
Content-Type: application/json

{
  "client_id": 1
}

###

# Return a book (POST)
POST http://localhost/v3/books/1/return
Content-Type: application/json

###

# List all clients (GET)
GET http://localhost/v3/clients
Content-Type: application/json

###

# Show a specific client (GET)
GET http://localhost/v3/clients/1
Content-Type: application/json

###

# Create a new client (POST)
POST http://localhost/v3/clients
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe"
}

###

# Delete a client (DELETE)
DELETE http://localhost/v3/clients/1
Content-Type: application/json
